[project]
name = "workout-streak-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "python-dotenv>=1.1.0",
    "python-telegram-bot==21.1",
    "redis==6.0.0b2",
]
